"""Second_migration

Revision ID: 23307e049b82
Revises: 97bebc826902
Create Date: 2025-04-13 14:31:29.881954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23307e049b82'
down_revision = '97bebc826902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
