"""Third_migration

Revision ID: 713f23527b0e
Revises: 23307e049b82
Create Date: 2025-04-13 14:58:52.995922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713f23527b0e'
down_revision = '23307e049b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
