"""empty message

Revision ID: f3439ff3785a
Revises: 713f23527b0e
Create Date: 2025-04-19 17:37:50.034989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3439ff3785a'
down_revision = '713f23527b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
